[package]
name = "wave-function-collapse"
version = "0.0.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.7.1", features = ["serde"] }
ndarray = "0.16.1"
photo = { path = "../photo" }
rand = "0.9.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
