[package]
name = "cartographer"
version = "0.0.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
crossterm = "0.28.1"
indicatif = "0.17.11"
ndarray = "0.16.1"
photo = "2.4.2"
rand = "0.9.0"
serde = "1.0.218"
serde_yaml = "0.9.34"
varisat = "0.2.2"
